### PR TITLE
Api unit test

### PR DESCRIPTION
**Pull request by Ahmed-Elawad**
Implemented testing suite to verify API responds to product request with accurate information.

### CODE REVIEW

**Review by hongmm — APPROVED** [review]
Looks good @Ahmed-Elawad! Not sure if I can see it or not but remember to leave a newline at the bottom of your files if you don't.

**Review by augustdolan — APPROVED** [review]
This is not a priority, but look into ignoring your package-lock and your main.js from webpack when you have some spare time. Hint: check out git rm -r --cache and what that can do for you. Be very careful not to execute if you don't have --cache.

Avoid async/await if you can. We're advised not to use it yet.

**Comment by Ahmed-Elawad** [comment]
@hongmm I think the rendering on git excludes the extra lines. The missing line seems to be indicated by a red "O" at the end of the file if there is no line.

**Comment by Ahmed-Elawad** [comment]
@augustdolan Thanks for the heads up! Went ahead and corrected the test suite.

**Pull request merged**
