### PR TITLE
Grid to carousel functionality

### PR DESCRIPTION
**Pull request by Ahmed-Elawad**
Image grid renders carousel modal on click of image elements.

### CODE REVIEW

**Comment by Ahmed-Elawad** [comment]
@augustdolan, Do you have a second to take a look at this implementation? I'm specifically interested in your thoughts of the conditional rendering of a component inheriting props like the carousel.

**Comment by augustdolan** [comment]
@Ahmed-Elawad On this now, sorry I didn't notice before

**Review by augustdolan — APPROVED** [review]
client/src/components/Imagecarousel.jsx

- Lines 34 & 40 have a syntax error

- Are you experiencing any issues bugs initializing your states to null? If not, no worries, but be wary in the future, that might be causing bugs (it did for me once).

- You've got a componentDidMount converting these from null - are you planning on pulling in your data her instead? If so, keep the nulls, they won't impact things.

**Comment by Ahmed-Elawad** [comment]
@augustdolan, I haven't had any issues with initializing the state with null since. The service pulls the data and passes it along to the child components: size, details, and images. I could only figure to have them inherit and pass data to their smaller components. Thanks for taking a look!

**Pull request merged**
